spring:
  datasource:
#    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    url: ${SPRING_DATASOURCE_URL}
    username: postgres.aqrdafhktexdpcfkqfeo
#    password: LeaveOfss@321
    password: ${SUPABASE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Useful for debugging - shows queries in console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
