spring:
  mongodb:
    uri: ${MONGODB_URI2}
#    uri: "mongodb+srv://shandilyavaibhav28_db_user:NVzGf0tCzsHCVHCy@airecommendationfitness.lbzzibh.mongodb.net/airecommendationfitness?appName=airecommendationfitness"
  kafka:
    bootstrap-servers: kafka-39123c4a-shandilyavaibhav28-6213.c.aivencloud.com:27665
    properties:
      security.protocol: SSL
      ssl.truststore.location: E:\Dev\microservices\fitness-microservices\certs\truststore.jks
      ssl.truststore.password: password123
      ssl.keystore.location: E:\Dev\microservices\fitness-microservices\certs\keystore.jks
      ssl.keystore.password: password123
      ssl.key.password: password123
      # Optional: Disable hostname verification if you get SSL handshake errors
      ssl.endpoint.identification.algorithm: ""
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # 🔑 THESE TWO ARE MANDATORY
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

kafka:
  topic:
    name: activity-events

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
